services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/TeamTrackr/Employees/Entity/'

    # Doctrine configuration
    Doctrine\ORM\EntityManager:
        factory: [ App\TeamTrackr\Shared\Infrastructure\Persistence\Doctrine\MoocEntityManagerFactory, create ]
        arguments:
            - driver: '%env(DATABASE_DRIVER)%'
              host: '%env(DATABASE_HOST)%'
              port: '%env(DATABASE_PORT)%'
              dbname: '%env(DATABASE_NAME)%'
              user: '%env(DATABASE_USER)%'
              password: '%env(DATABASE_PASSWORD)%'
            - '%env(APP_ENV)%'
        tags:
            - { name: database_connection }
        public: true

    # Dependency Injection
    App\TeamTrackr\Employees\Domain\EmployeeRepository: '@TeamTrackr\Employees\Infrastructure\Persistence\DoctrineEmployeeRepository'

    # Tagging
    App\TeamTrackr\Shared\Infrastructure\Doctrine\DatabaseConnections:
        arguments: [!tagged database_connection]

    # Controllers
    App\TeamTrackr\Employees\Infrastructure\Controller\:
        resource: '../src/TeamTrackr/Employees/Infrastructure/Controller/'
        tags: ['controller.service_arguments']